Class {
	#name : 'SmallChatFamixModel',
	#superclass : 'MooseModel',
	#traits : 'SmallChatFamixTEntityCreator',
	#classTraits : 'SmallChatFamixTEntityCreator classTrait',
	#category : 'SmallChat-Famix-Model',
	#package : 'SmallChat-Famix',
	#tag : 'Model'
}

{ #category : 'meta' }
SmallChatFamixModel class >> annotation [
	<FMClass: #SmallChatFamixModel super: #MooseModel>
	<package: #'SmallChat-Famix'>
	<generated>
]
